version: "3"

# Try `docker-compose up`

services:
    ovpn_proxy:
        image: jonoh/openvpn-proxy
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - ./config/:/config/
        env_file:
            - .env
        ports:
            - 8081:80
            - 8080:8080
        restart: always
